import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Image from "next/image";

import Footer from "./Layout/Footer";
import Header from "./Layout/Header";
import ThemeSwitcher from "./Layout/ThemeSwitcher";
import Providers from "./providers";

import "./globals.css";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/authOptions";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body className={`${inter.className} relative`}>
        <Providers session={session}>
          {children}
          <ThemeSwitcher />
        </Providers>
      </body>
    </html>
  );
}
